### ISSUE TITLE
wechat-test

### ISSUE THREAD

**Issue by NoBey** [youngon-cn/WeChat#1]
wechat-test  
去看下这里面的吧https://github.com/node-webot
wechat改用的都有了

**Comment by F-loat** [comment]
嗯，我之前做别的用过点那个，网站这个前端刚写的差不多，这两天把后端的东西加上

**Comment by NoBey** [comment]
前端长啥样我瞅瞅，地址多少

**Comment by F-loat** [comment]
wx.youngon.com.cn/history
wx.youngon.com.cn/forum
wx.youngon.com.cn/ygadmin

**Comment by F-loat** [comment]
forum这个是昨天做的，差不多了就让他们用这个吧

**Comment by NoBey** [comment]
用的vue啊

**Comment by F-loat** [comment]
嗯，这个ui框架还是vue1.0的，2.0的那个作者正在做

**Comment by NoBey** [comment]
ui库用的是啥

**Comment by F-loat** [comment]
我用的这个 https://github.com/myronliu347/vue-carbon
2.0的还没完成 https://github.com/museui/muse-ui

**Comment by NoBey** [comment]
昨天折腾了个好玩的aira2 加 yaaw
https://github.com/binux/yaaw
你就用网页控制服务器去下载东西

**Comment by F-loat** [comment]
嗯，我用的到再看吧，这两天先把这个弄了
